### ISSUE TITLE
Customize font unique font

### ISSUE THREAD

**Issue by TakumaNakagame** [skanehira/rtty#3]
I'm customizing zsh. And I'm also changing the 'font'.
The default font the browser displayed Tofu, so I want to customize the font unique to the this page.

![image](https://user-images.githubusercontent.com/5129906/117739762-f4826b80-b239-11eb-9110-54fdb325123b.png)

**Comment by skanehira** [comment]
@TakumaNakagame Hi, I supported for change font and font size in this PR.
Please update and try it :)
https://github.com/skanehira/rtty/pull/4
